[build-system]
requires = ["hatchling","numpy","polar","mysql-connector-python >= 8.1.0"]
build-backend = "hatchling.build"

[project]
name = "spray"
version = "0.1.3"
authors = [
  { name="banrieen", email="banrieen@163.com" },
]
description = "A data loader and anasysis tool"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
]
dependencies = [
    "sanic[ext]>=23.3.0",
]


[project.urls]
"Homepage" = "https://github.com/pypa/spray"
"Bug Tracker" = "https://github.com/pypa/spray/issues"
