[project]
name = "wave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "connectorx>=0.4.0",
    "mysql-connector-python>=9.1.0",
    "pandas>=2.2.3",
    "polars>=1.12.0",
    "pyarrow>=18.0.0",
    "sanic[ext]>=24.6.0",
    "toml>=0.10.2",
]
