# Data source config
# Env: Python 3.11.4

[LED_CSV_QIANZHAO.info]
csv_path = "C:\\workspace\\ProductManageSpace\\乾照-厦门评估数据"


[LED_CSV_QIANZHAO.analysis_info]
Index = "VF"
Spec = [0,0.3]
BINCode = "BIN"
asix = ["PosX","PosY"]
database = "datasets_led_qianzhao"
dut_info_table = "datasets_led_qianzhao.dut_info"
dut_list_table = "datasets_led_qianzhao.dut_list"
dut_summary_table = "datasets_led_qianzhao.dut_summary"
sheetID = 2
dut_info_row = 10
dut_list_row = 19
dut_list_count = ""

[LED_CSV_QIANZHAO.dataset_db]
host = "192.168.13.55"
port = "3306"
user = "root"
password = "root"
raise_on_warnings = true

[LED_CSV_QIANZHAO.minIO]
endpoint = "192.168.13.89:9000"
access_key = "BEUHvMfx9zXUpnD35wiO1xuyJwPvlULuVqljgIHz"
account = "admin"
secret_key = "admin123"
secure = false

[LED_CSV_QIANZHAO.dut_info]
FileName = "FileName"
TestStartTime = "TestStartTime"
TestEndTime = "TestEndTime"
TesterModel = "TesterModel"
TesterNumber = "TesterNumber"
Specification = "Specification"
TotalTested = "TotalTested"                                                                                              
Operator = "Operator"                                                

[LED_CSV_QIANZHAO.dut_list]
TEST = "TEST"
BIN = "BIN" 
VF1 = "VF1"
IR1 = "IR1"
PosX = "PosX"
PosY = "PosY"

[LED_CSV_QIANZHAO.dut_join]
FileName = "FileName"   
Operator = "Operator"   
TesterModel = "TesterModel"  

[LED_CSV_QIANZHAO.dut_summary]
STARTTESTT = "STARTTESTT"
COMPONENTID = "COMPONENTID"
"外延机台" = "外延机台"
PROBER_RECORD_SID = "PROBER_RECORD_SID"
WAFERQTY = "WAFERQTY"
ELE_YIELD = "ELE_YIELD"
OPERATORID = "OPERATORID"
STARTTESTTIME = "STARTTESTTIME"
ENDTESTTIME = "ENDTESTTIME"
MACHINENO = "MACHINENO"
UPDATETIME = "UPDATETIME"
VF1_MIN = "VF1_MIN"
VF1_AVG = "VF1_AVG"
VF1_MAX = "VF1_MAX"
VF1_STD = "VF1_STD"
VF1_YIELD = "VF1_YIELD"
VF2_MIN = "VF2_MIN"
VF2_AVG = "VF2_AVG"
VF2_MAX = "VF2_MAX"
VF2_STD = "VF2_STD"
VF2_YIELD = "VF2_YIELD"
VF3_MIN = "VF3_MIN"
VF3_AVG = "VF3_AVG"
VF3_MAX = "VF3_MAX"
VF3_STD = "VF3_STD"
VF3_YIELD = "VF3_YIELD"
VF4_MIN = "VF4_MIN"
VF4_AVG = "VF4_AVG"
VF4_MAX = "VF4_MAX"
VF4_STD = "VF4_STD"
VF4_YIELD = "VF4_YIELD"
VF5_MIN = "VF5_MIN"
VF5_AVG = "VF5_AVG"
VF5_MAX = "VF5_MAX"
VF5_STD = "VF5_STD"
VF5_YIELD = "VF5_YIELD"
VFM2_MIN = "VFM2_MIN"
VFM2_AVG = "VFM2_AVG"
VFM2_MAX = "VFM2_MAX"
VFM2_STD = "VFM2_STD"
VFM2_YIELD = "VFM2_YIELD"
DVF_MIN = "DVF_MIN"
DVF_AVG = "DVF_AVG"
DVF_MAX = "DVF_MAX"
DVF_STD = "DVF_STD"
DVF_YIELD = "DVF_YIELD"
VF_MIN = "VF_MIN"
VF_AVG = "VF_AVG"
VF_MAX = "VF_MAX"
VF_STD = "VF_STD"
VF_YIELD = "VF_YIELD"
VFD_MIN = "VFD_MIN"
VFD_MAX = "VFD_MAX"
VFD_STD = "VFD_STD"
VFD_YIELD = "VFD_YIELD"
VZ1_MIN = "VZ1_MIN"
VZ1_AVG = "VZ1_AVG"
VZ1_MAX = "VZ1_MAX"
VZ1_STD = "VZ1_STD"
VZ1_YIELD = "VZ1_YIELD"
IR1_MIN = "IR1_MIN"
IR1_AVG = "IR1_AVG"
IR1_MAX = "IR1_MAX"
IR1_STD = "IR1_STD"
IR1_YIELD = "IR1_YIELD"
IR2_MIN = "IR2_MIN"
IR2_AVG = "IR2_AVG"
IR2_MAX = "IR2_MAX"
IR2_STD = "IR2_STD"
IR2_YIELD = "IR2_YIELD"
LOP1_MIN = "LOP1_MIN"
LOP1_AVG = "LOP1_AVG"
LOP1_MAX = "LOP1_MAX"
LOP1_STD = "LOP1_STD"
LOP1_YIELD = "LOP1_YIELD"
LOP2_MIN = "LOP2_MIN"
LOP2_AVG = "LOP2_AVG"
LOP2_MAX = "LOP2_MAX"
LOP2_STD = "LOP2_STD"
LOP2_YIELD = "LOP2_YIELD"
LOP3_MIN = "LOP3_MIN"
LOP3_AVG = "LOP3_AVG"
LOP3_MAX = "LOP3_MAX"
LOP3_STD = "LOP3_STD"
LOP3_YIELD = "LOP3_YIELD"
LOP4_MIN = "LOP4_MIN"
LOP4_AVG = "LOP4_AVG"
LOP4_MAX = "LOP4_MAX"
LOP4_STD = "LOP4_STD"
LOP4_YIELD = "LOP4_YIELD"
LOP5_MIN = "LOP5_MIN"
LOP5_AVG = "LOP5_AVG"
LOP5_MAX = "LOP5_MAX"
LOP5_STD = "LOP5_STD"
LOP5_YIELD = "LOP5_YIELD"
WLP1_MIN = "WLP1_MIN"
WLP1_AVG = "WLP1_AVG"
WLP1_MAX = "WLP1_MAX"
WLP1_STD = "WLP1_STD"
WLP1_YIELD = "WLP1_YIELD"
WLD1_MIN = "WLD1_MIN"
WLD1_AVG = "WLD1_AVG"
WLD1_MAX = "WLD1_MAX"
WLD1_STD = "WLD1_STD"
WLD1_YIELD = "WLD1_YIELD"
WLC1_MIN = "WLC1_MIN"
WLC1_AVG = "WLC1_AVG"
WLC1_MAX = "WLC1_MAX"
WLC1_STD = "WLC1_STD"
WLC1_YIELD = "WLC1_YIELD"
HW1_MIN = "HW1_MIN"
HW1_AVG = "HW1_AVG"
HW1_MAX = "HW1_MAX"
HW1_STD = "HW1_STD"
HW1_YIELD = "HW1_YIELD"
PURITY1_MIN = "PURITY1_MIN"
PURITY1_AVG = "PURITY1_AVG"
PURITY1_MAX = "PURITY1_MAX"
PURITY1_STD = "PURITY1_STD"
PURITY1_YIELD = "PURITY1_YIELD"
WLP2_MIN = "WLP2_MIN"
WLP2_AVG = "WLP2_AVG"
WLP2_MAX = "WLP2_MAX"
WLP2_STD = "WLP2_STD"
WLP2_YIELD = "WLP2_YIELD"
WLD2_MIN = "WLD2_MIN"
WLD2_AVG = "WLD2_AVG"
WLD2_MAX = "WLD2_MAX"
WLD2_STD = "WLD2_STD"
WLD2_YIELD = "WLD2_YIELD"
ESD_HBM_YIELD = "ESD_HBM_YIELD"
ESD_MM_YIELD = "ESD_MM_YIELD"
